name: Auto-label tiny & safe PRs as bot-suggest
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'src/**'
      - 'docs/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        uses: cli/gh-action@v2

      - name: Decide and label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: "200"     # must match your bot safety limits
          MAX_FILES: "5"
        run: |
          set -e
          PR=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          
          # Get PR stats
          json=$(gh api repos/$REPO/pulls/$PR)
          add=$(echo "$json" | jq -r '.additions')
          del=$(echo "$json" | jq -r '.deletions')
          files=$(echo "$json" | jq -r '.changed_files')
          size=$(( add + del ))
          
          echo "PR #$PR add:$add del:$del changed_files:$files total_delta:$size"
          
          # Only label if tiny AND no existing bot-suggest
          has_label=$(echo "$json" | jq -r '[.labels[].name] | index("bot-suggest")')
          if [ "$has_label" != "null" ]; then
            echo "Already labeled bot-suggest; skipping."
            exit 0
          fi
          
          if [ "$size" -le "$MAX_LINES" ] && [ "$files" -le "$MAX_FILES" ]; then
            gh pr edit $PR --add-label bot-suggest
            echo "✅ Auto-labeled bot-suggest (size: $size lines, files: $files)"
            
            # Add a helpful comment
            gh pr comment $PR --body "🤖 **Auto-labeled \`bot-suggest\`**

This PR is small enough (≤${MAX_LINES} changed lines, ≤${MAX_FILES} files) and only touches safe paths (\`src/**\`, \`docs/**\`), so it's eligible for AI bot patch suggestions.

The AI bot will analyze this PR and may propose a tiny, safe improvement as a draft PR."
          else
            echo "PR too large for bot-suggest (size>$MAX_LINES or files>$MAX_FILES)."
          fi
